# Generated by Django 3.2.4 on 2021-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='user',
        ),
        migrations.AddField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='username',
            field=models.CharField(default='Hello', max_length=50),
            preserve_default=False,
        ),
    ]
